#!/bin/bash
S3TEST_CONF=./s3tests.conf
ROOT_PATH=`pwd`
source "${ROOT_PATH}/virtualenv/bin/activate"
NOSE_BIN=

#BUCKET
nosetests s3tests_boto3.functional.test_s3:test_bucket_list_empty
nosetests s3tests_boto3.functional.test_s3:test_bucket_list_distinct
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_many
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_basic
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_encoding_basic
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_prefix
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_prefix_ends_with_delimiter
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_alt
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_prefix_underscore
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_percentage
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_whitespace
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_dot
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_unreadable
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_empty
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_none
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_fetchowner_notempty
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_fetchowner_defaultempty
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_fetchowner_empty
nosetests s3tests_boto3.functional.test_s3:test_bucket_listv2_delimiter_not_exist
nosetests s3tests_boto3.functional.test_s3:test_bucket_list_delimiter_not_skip_special
nosetests s3tests_boto3.functional.test_s3:test_bucket_list_delimiter_not_skip_special


#OBJECT


deactivate
